# Deep Learning
  * when ML fails to work then only Deeplearning comes to the picture .
  * It consist of Neural network.
  * What is neuron, connection of neurons called as Neural Network.


  ### There are three typtes :
                            * ANN
                            * CNN
                            * RNN

    * Ann work on Structered data set .
    * Cnn works on images .   
    * Rnn works on speech or text .

# Neural Network Architecture :
    * Single neural network Architectutre 
    * Multi neural network Architecture 

* Architecture are build of three layer INPUT LAYER, HIDDEN LAYER,   OUTPUT LAYER.

* I/P - H/L - O/L (Single layer Architecture)

* I/P - H/L1 - H/L2 - H/L3 - O/P (Multi layer Architecture)

#### Epochs = forward Propagation + Backwrad Propagation 

* when we send/pass  signal from 1 neuron to another neuron  weight will assign  at FP(forward Propagation) .

* in BACKPROPAGATION  weight are Adjusted .

* when we do more number of epochs  accuracy will increase .



# Ann(Artificial Neural Network)
* An Artificial Neural Network is a model inspired by how the human brain works.
* It consists of layers of “neurons” that learn patterns from data. 

###  Activation function 
* Activation function will implement in Hidden layer and output layer .
* Sigmoid activation function(apply on output layer and it adjust outlier (Range=0 to 1))
* tanh activation(apply on o/p layer (Range = -1 to 1))
* Relu(Rectifier function) activation function (Formula (max(x,o))) here you will never get any -ve value. it apply on only hidden layer(RAnge = 0 to infinity).
* Leeky relu (While the data has any -ve values then we apply leeky relu). it alsoapply in hidden liyer .(Range = -1 to infinity)
* softmax(is  apply on o/p layer (* if thereis binary class thn apply sigmoidand if there is multiclass thn apply Softmax)).. the main advantage of using this is the output is in probabilities range (0 to 1).

* N.B : Except  softmax all  function are apply on binnary classification .
* we not apply every activation one time .

* Inteview Questions : Sigmoid fun vs tanh fun   and  relu vs leeky relu

### Formula : 
 * new weight = old weight - learningrate * (derivation of loss/derivation of old weight)

* Simple example

If:

    old weight = 0.5
    learning rate = 0.1
    gradient = 0.2

Then:


    new weight = 0.5 - (0.1 × 0.2)
           = 0.5 - 0.02
           = 0.48

### Venishing Gradiant Descend:
* new weight == old weight that problem is called vanishing gradiant descend(vgd) it causes the  stop of the epoc then accuracy will Decrease.
* why the vgd problem occours coz overfits of neural model (Here overfits means -Trend the model with more neuron) to tackle this type of situation we apply Dropout(Drop the neurons) or Reagularization(lasso,Redge) 


# Code

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.21.0'

In [3]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
dataset

,apst,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,delhi,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,bangalore,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,delhi,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,delhi,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,bangalore,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,delhi,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,delhi,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,delhi,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,mumbai,Male,42,3,75075.31,2,1,0,92888.52,1


In [16]:
dataset.head()

,apst,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,delhi,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,bangalore,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,delhi,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,delhi,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,bangalore,Female,43,2,125510.82,1,1,1,79084.10,0


In [6]:
X

array([[619, 'delhi', 'Female', ..., 1, 1, 101348.88],
       [608, 'bangalore', 'Female', ..., 0, 1, 112542.58],
       [502, 'delhi', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'delhi', 'Female', ..., 0, 1, 42085.58],
       [772, 'mumbai', 'Male', ..., 1, 0, 92888.52],
       [792, 'delhi', 'Female', ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0], shape=(10000,))

In [8]:
import sys
print(sys.executable)

!"{sys.executable}" -m pip install scikit-learn

c:\Users\Satyabrata Sahoo\AppData\Local\Programs\Python\Python310\python.exe



[notice] A new release of pip available: 22.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [20]:
X

array([[0.0, 1.0, 0, ..., 1, 1, 101348.88],
       [1.0, 0.0, 1, ..., 0, 1, 112542.58],
       [0.0, 1.0, 0, ..., 1, 0, 113931.57],
       ...,
       [0.0, 1.0, 0, ..., 0, 1, 42085.58],
       [1.0, 0.0, 1, ..., 1, 0, 92888.52],
       [0.0, 1.0, 0, ..., 1, 0, 38190.78]],
      shape=(10000, 14), dtype=object)

In [21]:
y

array([1, 0, 1, ..., 1, 1, 0], shape=(10000,))

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
X

array([[0.0, 1.0, 0.0, ..., 1, 1, 101348.88],
       [1.0, 0.0, 0.0, ..., 0, 1, 112542.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [0.0, 1.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 0.0, 1.0, ..., 1, 0, 92888.52],
       [0.0, 1.0, 0.0, ..., 1, 0, 38190.78]],
      shape=(10000, 12), dtype=object)

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [14]:
X

array([[0.0, 1.0, 0.0, ..., 1, 1, 101348.88],
       [1.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [0.0, 1.0, 0.0, ..., 0, 1, 42085.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 92888.52],
       [0.0, 1.0, 0.0, ..., 1, 0, 38190.78]],
      shape=(10000, 13), dtype=object)

In [23]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)

In [24]:
X

array([[-0.99720391,  0.99720391, -0.99720391, ...,  0.64609167,
         0.97024255,  0.02188649],
       [ 1.00280393, -1.00280393,  1.00280393, ..., -1.54776799,
         0.97024255,  0.21653375],
       [-0.99720391,  0.99720391, -0.99720391, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [-0.99720391,  0.99720391, -0.99720391, ..., -1.54776799,
         0.97024255, -1.00864308],
       [ 1.00280393, -1.00280393,  1.00280393, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [-0.99720391,  0.99720391, -0.99720391, ...,  0.64609167,
        -1.03067011, -1.07636976]], shape=(10000, 15))

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [26]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 15)
(2000, 15)
(8000,)
(2000,)


# ANN MODEL BUILDING ARCHITECTURE

In [27]:
ann = tf.keras.models.Sequential() #establishing layer one after another

* Here we  built a neutral network 
    * tf = backend 
    * keras = frontend
    * sequential means establish of the layers(i.e. created layer in memory)


In [28]:
ann.add(tf.keras.layers.Dense(units=10)) # input layer

* unit= 6 (i.e. 6 neurons in i/p layers)
* Dense is connected the neuronsto the layers .


In [29]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu')) # Hidden layer1

In [30]:
ann.add(tf.keras.layers.Dense(units=5, activation='relu')) #2nd hidden layer

In [31]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) #output layer

#### optimoizer in Ann:
 * socastic gradient descend
 * adam
 * adagrad
 * adadelta
 * adamax
 * rmsprop

#### Loss :
  * regression loss --- mae,mse,logloss
  * classification  loss --- binary cross entropy, category cross entropy, sparse category cross entropy

In [32]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [33]:

ann.fit(X_train,y_train,batch_size=32,epochs=50)

Epoch 1/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7588 - loss: 0.5371
Epoch 2/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7999 - loss: 0.4510
Epoch 3/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8070 - loss: 0.4336
Epoch 4/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8185 - loss: 0.4239
Epoch 5/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8251 - loss: 0.4160
Epoch 6/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8282 - loss: 0.4102
Epoch 7/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8317 - loss: 0.4053
Epoch 8/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8347 - loss: 0.4013
Epoch 9/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8351 - loss: 0.3975
Epoch 10/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8363 - loss: 0.3935
Epoch 11/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8361 - loss: 0.3881
Epoch 12/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [34]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [35]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1540   55]
 [ 209  196]]


In [36]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)

0.868
